#!/usr/bin/python

import os
import time
import sys
import itertools
import locale
from basicelements import *
from notification import Notification

DEFAULTARGS = ("-ta r -y 782 -w 1100 -x 180 -bg black -fn "
                "lucida:weight=bold:pixelsize=12 "
                "-e 'button1=exec:notify-send CLEARNOTIFICATIONS'")
ELEMENTS = (Notification(size=25), MpdPlayer(size=40, scroll=1),
        DiskUsage(), Audio(), Memory(), Battery(), Load(), Time())

def main():
    locale.setlocale(locale.LC_ALL, locale.getdefaultlocale())
    dzenproc = os.popen("dzen2 " + DEFAULTARGS + " ".join(sys.argv[1:]), "w")
    for line in itertools.izip(*ELEMENTS):
        dzenproc.write(" ".join(line) + "\n")
        dzenproc.flush()
        time.sleep(1)

if __name__ == "__main__":
    main()
